export const POST_NEW_CAR = 'POST_NEW_CAR';
export const POST_NEW_CAR_SUCCESS = 'POST_NEW_CAR_SUCCESS';
export const POST_NEW_CAR_FAILURE = 'POST_NEW_CAR_FAILURE';
export const POST_NEW_WORKER_SUCCESS = 'POST_NEW_WORKER_SUCCESS';
export const POST_NEW_WORKER_FAILURE = 'POST_NEW_WORKER_FAILURE';
export const POST_NEW_WORKER = 'POST_NEW_WORKER';