export const LOAD_WORKER = 'LOAD_WORKER';
export const LOAD_WORKER_SUCCESS = 'LOAD_WORKER_SUCCESS';
export const LOAD_WORKER_FAILURE = 'LOAD_WORKER_FAILURE';
export const EDIT_WORKER = 'EDIT_WORKER';
export const EDIT_WORKER_SUCCESS = 'EDIT_WORKER_SUCCESS';
export const EDIT_WORKER_FAILURE = 'EDIT_WORKER_FAILURE';
